#!/usr/bin/env bash
#
# create-php-ini.sh - Generate php-custom.ini for WordPress
#
#==============================================================================

set -euo pipefail

if [[ "${GENERATE_PHP_INI:-false}" != "true" ]]; then
    exit 0
fi

TARGET_DIR="${1:-.}"

cat > "$TARGET_DIR/php-custom.ini" <<EOF
; Custom PHP Configuration for WordPress
; Generated by WordPress Site Generator

; File Uploads
upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}
post_max_size = ${PHP_POST_MAX_SIZE}

; Memory Limits
memory_limit = ${PHP_MEMORY_LIMIT}

; Execution Limits
max_execution_time = ${PHP_MAX_EXECUTION_TIME}
max_input_time = ${PHP_MAX_INPUT_TIME}

; Error Reporting (disable in production)
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
log_errors = On

; OpCache (for performance)
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 2

; Session Settings
session.save_path = /tmp
session.gc_maxlifetime = 1440

; Date Timezone
date.timezone = UTC
EOF

echo "Created php-custom.ini in $TARGET_DIR"