#!/usr/bin/env bash
#
# create-nginx-site.sh - Generate nginx site configuration for WordPress in Docker
#
# DESCRIPTION:
#   Creates an nginx site configuration file for WordPress running in Docker
#   on the host system. Uses variables for domain, project name, and upload limits.
#
# USAGE:
#   ./create-nginx-site.sh
#
# DEPENDS ON:
#   PROJECT_NAME, DOMAIN, PORTWP, NGINX_CLIENT_MAX_BODY_SIZE
#
#==============================================================================

set -euo pipefail

# Load configuration (if running independently)
if [[ -f "./wordpress.sh" ]]; then
    source ./wordpress.sh
fi

# Set defaults if not defined
PROJECT_NAME="${PROJECT_NAME:-wordpress_project}"
DOMAIN="${DOMAIN:-localhost}"
PORTWP="${PORTWP:-8080}"
NGINX_CLIENT_MAX_BODY_SIZE="${NGINX_CLIENT_MAX_BODY_SIZE:-64M}"

# Target file
NGINX_SITE_FILE="/etc/nginx/sites-available/${PROJECT_NAME}.conf"

# Create the nginx site configuration
sudo tee "$NGINX_SITE_FILE" > /dev/null <<EOF
# Nginx configuration for WordPress in Docker
# Generated by WordPress Site Generator
# Project: ${PROJECT_NAME}

# Upstream to WordPress PHP-FPM (Docker container)
upstream ${PROJECT_NAME}_php {
    server unix:/run/php/php8.2-fpm.sock;
    server 127.0.0.1:${PORTWP};
}

server {
    listen 80;
    server_name ${DOMAIN} www.${DOMAIN};
    
    # Root directory
    root /var/www/html;
    index index.php index.html;
    
    # Client max body size (for file uploads)
    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};
    
    # Logging
    access_log /var/log/nginx/${PROJECT_NAME}-access.log;
    error_log /var/log/nginx/${PROJECT_NAME}-error.log;

    location / {
        proxy_pass http://localhost:${PORTWP};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }


    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        proxy_pass http://localhost:${PORTWP};
        expires max;
        log_not_found off;
        access_log off;
    }

    # Deny access to sensitive WordPress files
    location ~ /\.ht {
        deny all;
    }

    location ~ /wp-config.php {
        deny all;
    }

    location ~ /wp-content/uploads/.*\.php$ {
        deny all;
    }
        
}

EOF

echo "Created nginx site configuration: $NGINX_SITE_FILE"

# Enable the site
if [[ -f "/etc/nginx/sites-enabled/${PROJECT_NAME}.conf" ]]; then
    echo "Site already enabled."
else
    sudo ln -s "$NGINX_SITE_FILE" "/etc/nginx/sites-enabled/${PROJECT_NAME}.conf"
    echo "Enabled site: ${PROJECT_NAME}.conf"
fi

# Test nginx configuration
echo "Testing nginx configuration..."
sudo nginx -t

if [[ $? -eq 0 ]]; then
    echo "Configuration test passed."
    echo "Reload nginx to apply changes: sudo systemctl reload nginx"
else
    echo "Configuration test failed. Please check the syntax."
    exit 1
fi